name: The Chill Project
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6403811234049499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#45b4e2'
    - '#396372'
    - '#acacac'
  brandStrength: 0.8849674721714109
  lightness: 0.1255251185502857
  saturation: 0.8517693181056529
  rhythmicContrast: 0.26126433443278074
purpose: []
